[build]
  base = "core/template"
  command = "npm run build:site"
  publish = "core/template/dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200
