backend:
  name: git-gateway
  branch: master

media_folder: 'public/img/uploads'
public_folder: '/img/uploads'

collections:

  # default blog posts collection
  # remove if your template does not support blog
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    extension: 'json'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Featured Image', name: 'thumbnail', widget: 'image'}
      - {label: 'Short Description', name: 'description', widget: 'text'}
      - {label: 'Body', name: 'body', widget: 'markdown'}

  # general site settings
  # usually will be the same for any template
  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'content/settings.json'
        description: 'General Site Settings'
        fields:
          - {label: 'Name', name: 'name', widget: 'string'}
          - {label: 'Logo', name: 'logo', widget: 'image'}
          - {label: 'Primary Color', name: 'primary_color', widget: 'string'}
          - {label: 'Secondary Color', name: 'secondary_color', widget: 'string'}
          - {label: 'Icon', name: 'icon', widget: 'image'}
          - {label: 'Large Icon', name: 'large_icon', widget: 'image'}
          - {label: 'Favicon', name: 'favicon', widget: 'image'}
