name: Lighthouse

on:
  pull_request:
    types: [review_requested]
    branches:
      - master
    paths:
      - 'template/**'
      - 'content/**'

jobs:
  lighthouse:
    name: Audit new site deploy preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          urls: |
            https://deploy-preview-$PR_NUMBER--storefront-template.netlify.com/
          temporaryPublicStorage: true
