name: Lighthouse

on:
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    name: Audit homepage using Lighthouse
    runs-on: ubuntu-latest

    steps:
      - name: Test Netlify deploy preview
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: 'storefront-template.netlify.com'

      - name: Save report artifact
        uses: actions/upload-artifact@v1
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          name: lighthouse
          path: lighthouse-report-$PR_NUMBER
